### ISSUE TITLE
Discrepancy between "I.txt" and the code

### ISSUE THREAD

**Issue by yaoxinreaps** [anastasia-tkach/hmodel-cpp-public#1]
Hi, Mr. Tkach,
I found that there seem's to be something wrong in the data filefold "./data/models/anastasia/*.txt" or somewhere else in the code. For example, in the function "load_model_from_file()" in "Model.cpp", 'i' ranges from 0 to N-1 (N is 19 read from "I.txt"), but the size of 'phalanges' is set to 18 in the code. So the subscript will be out of range in "fscanf(fp, "%f", &phalanges[i].init_local(v, u))" when 'i' is 18. And this kind of error can also be found in somewhere else in the code. Would you please take a review of the code and give me a reply? Thank you very much!

**Comment by anastasia-tkach** [comment]
Hello, thanks for spotting a problem. 
The whole set of data structures for hand model is a mess, it is a legacy from several people developing at the same time. I have already cleaned it up in the next  version of this project which will be online in several month. So, I probably will not spend time to fix it here.
There is different number of phalanges in different places in the code because the last phalange is only there to uniformly scale the model and is not actually needed in most cases.

**Comment by yaoxinreaps** [comment]
Thank you for your reply and sorry for my improper call on you as "Mr.". And here I have another problem. I established the project with vs2013 + cuda7.5 + win10 + nvidia gt630. But it went wrong in the simple function "resize()" in the type of "device_vector<>" (specifically as "J->resize()" and "F->resize" in function "kernel_init()") in either debug or release mode. I can't find the reason. Is it possible that the GPU is too old? Would you please give some advices? Thank you!

**Comment by anastasia-tkach** [comment]
"Thank you for your reply and sorry for my improper call on you as "Mr.". And here I have another problem. I established the project with vs2013 + cuda7.5 + win10 + nvidia gt630. But it went wrong in the simple function "resize()" in the type of "device_vector<>" (specifically as "J->resize()" and "F->resize" in function "kernel_init()") in either debug or release mode. I can't find the reason. Is it possible that the GPU is too old? Would you please give some advices? Thank you!"

Hello!
We have only tested the system with vs2013 + cuda7.0 + win8 + nvidia GeForce 980. This only thing I can advise is to make sure all the relevant helloworld applications run with you setup before trying to run the hand tracking system. Preferably get the applications from here https://github.com/OpenGP/htrack/tree/master/apps, since they were not tested for the new version of the project. 
But even if you manage to run the system with an older GPU, the odds are that it will not run it real time (60 FPS).

**Comment by yaoxinreaps** [comment]
Thank you for your advices again. Now I have run the program successfully. But I find the result is not so good as presented in your video demo either in live mode or in running the frame sequences (the size of hand model is adjusted to fit the depth data). The hand model oscillates frequently and it seems to have no improvement when I increase the weight of "temporal_coherence". Is it because the weights of energies are not correct? Or the GPU (gt630) is too old (it seems to run even less than 30fps)?

**Comment by anastasia-tkach** [comment]
The performance becomes much worse with lower frame rate, the whole idea of our system is to run local optimization initialized with the result of previous frame. This requires previous frame to be similar to the current frame. Also, the hand model that I provided with code is for my hand, so the performance should go down for your hand. Are you using RealSense by Intel? If not, the performance should also go down because of worse sensor data quality.
